sudo: required
dist: xenial
before_install:
  - sudo apt-get install openmpi-bin libopenmpi-dev
language: cpp
compiler:
  - gcc
install:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 -O eigen-3.3.7.tar.bz2 && mkdir eigen && tar -xvf eigen-3.3.7.tar.bz2 -C eigen --strip-components 1
script:
  - cd tutorial      && make clean     && make run && cd ..
  - TTOR_ROOT=${HOME}/build/leopoldcambier/tasktorrent ./tests/shared/run_tests_travis.sh
  - TTOR_ROOT=${HOME}/build/leopoldcambier/tasktorrent ./tests/mpi/run_tests_travis.sh
